services:
  strapi:
    build: .
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: 'development'
      DATABASE_CLIENT: 'postgres'
      DATABASE_HOST: 'postgres'
      DATABASE_PORT: 5432
      DATABASE_NAME: 'strapi'
      DATABASE_USERNAME: 'strapi'
      DATABASE_PASSWORD: 'strapi'
      DATABASE_SSL: 'false'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
